<?php

namespace Mapper;
require_once 'FixtureBasedTestCase.php';
require_once '../../lib/AbstractDataMapper.php';
require_once '../fixtures/User.php';

class UserMapper extends AbstractDataMapper{
    protected $entityTable = "users";
    
    public function __construct() {
        $this->model = new \User;
    }
    
}
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-22 at 09:33:54.
 */
class AbstractDataMapperTest extends \FixtureBasedTestCase {

    /**
     * @var AbstractDataMapper
     */
    protected $mapper;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->mapper = new UserMapper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testFindByIdReturnsEntity() {
        
    }

    /**
     * @covers Mapper\AbstractDataMapper::findAll
     * @todo   Implement testFindAll().
     */
    public function testFindAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Mapper\AbstractDataMapper::insert
     * @todo   Implement testInsert().
     */
    public function testInsertNewModel()
    {
        $model = new \User; 
        $model->name = "Farha";
        $model->email = "farha@alwaily.com";

        $this->mapper->insert($model);
        $this->assertTrue($model->id > 0);
    }

}
