<?php

namespace Model;
require_once '../../lib/AbstractDomainModel.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-21 at 12:21:36.
 */
class AbstractDomainModelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractDomainModel
     */
    private $model;
    
    private $modelData = array(
        "id" => "5",
        "name" => "Farha",
        "email" => "farha@elwailly.com"
        
        );

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->model = new AbstractDomainModel;
        $this->model->load($this->modelData);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testPropertiesCanBeReadMagically(){
        $this->assertSame($this->modelData['name'], $this->model->name);
        $this->assertSame($this->modelData['email'], $this->model->email);
    }
    
    public function testUnknownFieldsReturnsException(){
        //$this->model->UnknownField; //get magic method
        //$this->model->UnknownField = 5; //set magic method
    }
    
    public function testToArrayReturnsData(){
        $this->assertSame($this->modelData, $this->model->toArray());
        //print_r($this->model->toArray());
    }
    
    public function testFieldsCanBeSet(){
        $this->model->name = "fawaz";
        $this->assertSame("fawaz", $this->model->name);
    }

}
