<?php

namespace DatabaseLibrary;

require_once 'FixtureBasedTestCase.php';
require_once '../../lib/Database.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-08 at 14:48:18.
 */
class DatabaseTest extends \FixtureBasedTestCase {

    /**
     * @var Database
     */
    protected $db;
    protected $entityTable = "article";

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        parent::setUp();
        $dsn = sprintf("mysql:dbname=%s;host=%s", $this->dbName, $this->host);
        $this->db = new Database($dsn,$this->username, $this->password);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
}