<?php

namespace Mapper;
require_once "../../mapping/AbstractDataMapper.php";
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-07 at 13:27:25.
 */
class AbstractDataMapperTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var AbstractDataMapper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new AbstractDataMapper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Mapper\AbstractDataMapper::getDb
     * @todo   Implement testGetDb().
     */
    public function testGetDb() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Mapper\AbstractDataMapper::findById
     * @todo   Implement testFindById().
     */
    public function testFindById() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Mapper\AbstractDataMapper::findAll
     * @todo   Implement testFindAll().
     */
    public function testFindAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
